name: Executable package

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          if [ -f non-GUI/reqs.txt ]; then pip install -r non-GUI/reqs.txt; fi
      - name: Test with pytest
        run: pyinstaller --help
      - name: Upload pytest test results
        uses: actions/upload-artifact@v3
        with:
          name: mc-pc-ac-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}.*
          path: dist/mc-pc-ac-${{ matrix.os }}-${{ matrix.architecture }}-${{ matrix.python-version }}.*
        # Use always() to always run this step to publish test results when there are test failures
        if: ${{ always() }}
